export const emptyMortgageRequest = {
  id: null,
  creationTime: "",
  owner: null,
  borrowers: [
    {
      identityCardNumber: null,
      firstName: "",
      lastName: "",
      birthDate: "",
      phoneNumber: "",
      email: "",
      maritalStatus: "",
      childrenUnderAge21: 0,
      employmentData: [
        {
          employmentType: "HIRED_EMPLOYEE",
          placeOfEmployment: "",
          position: "",
          durationOfEmploymentInYears: 0,
          monthlySalary: 0,
          yearlySalary: 0,
        },
      ],
      spendings: [],
      extraIncomes: [],
      extraInfo: null,
    },
  ],
  guarantees: [],
  realEstateProperty: {
    location: "",
    propertyType: "",
    propertyStatus: "",
    price: 0,
    value: 0,
  },
  mortgageComposition: {
    loans: [],
    totalAmount: 0,
  },
  mortgageStatus: "IN_PROGRESS",
  customerDocumentsDirectory: null,
  isPulled: false,
  pulledBy: null,
  decisions: [],
  transferTime: "",
  queueType: "INITIAL",
};
